config/routes.rb
Porthos::Application.routes.draw do
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  

  mount Spree::Core::Engine, at: '/store'
  
  get '/admin', to: 'spree/admin/products#index', as: :admin
  get "/about_us", to: "storefront#about", as: :about
  get "/collection", to: "collection#index", as: :collection
  
  
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      get "products/data_import" => "products#data", as: :data_import
      get "website_photos" => "website_photos#index", as: :website_photos
      get "catalog" => "website_photos#catalog", as: :catalog
      post "import/inventory" => "products#bulk_import", as: :import_inventory
      post "import/variant_photos" => "products#import_images", as: :generate_variant_photos
      resources :hero_images do
        collection do
          post :update_positions
        end
      end
      resources :catalog_pages do
        collection do
          post :update_positions
        end
      end
    end
  end

  
  resources :customers, only: [:index]
  resources :products, only: [] do
    get :count_on_hand, on: :member
  end
  
  get "storefront/catalog" => "storefront#catalog", as: :download_catalog

  root to: 'storefront#index'

end

app/helpers/products_helper.rb
module ProductsHelper
  
  def active_select_thumbnail_background(variant, i)
    content_tag :div, 
                 variant_primary_thumbnail_url(variant),
                 id: "variant-#{variant.id}", class: "active-select-color-surface variant-description #{default_thumbnail_bg(variant)}",
                 data: { color: color_options(variant).downcase, thumb: variant.primary_thumbnail_url }
    
  end
  
  def admin_showcased_products_label
    dat_label = "#{Spree.t(:showcase)}?"
    return dat_label if Spree::Product.showcased_items.size < Spree::Product.allowed_showcase_items
    "#{dat_label} (At Max)"
  end
  
  # Displays swatch background iff no images exist for variant
  def default_thumbnail_bg(v)
    color_options(v).downcase unless v.images.any?
  end
  
  def lifestyle_background_image(product)
    product.lifestyle_shot? ? image_tag(variant.images.first.attachment.url(:product)) : "musketeer.png"
  end
  
  def next_page_button(on_last_pg, is_remote, url)
    on_last_pg ? page_decoy("next") : next_page_link(is_remote, url)
  end
  def prev_page_button(on_first_pg, is_remote, url)
    on_first_pg ? page_decoy("previous") : prev_page_link(is_remote, url)
  end
  
  def showcased_check_box(f)
    if disable_showcase_option?
      f.check_box :showcased, class: 'form-control', disabled: 'true'
    else
      f.check_box :showcased, class: 'form-control'
    end
  end
  
  def specifications
    # Remove properties that are ambiguous 'Features' (to be used in another section)
    @features           = @product_properties.select{|pp| pp.property.name =~ /features/i }
    @product_properties = @product_properties - @features
    # Remove properties with blank values
    @product_properties.reject{|s| s.value.blank? }
  end
  
  def variant_primary_thumbnail_url(v)
    if v.primary_thumbnail_url
      image_tag(v.primary_thumbnail_url, class: "thumbnail") 
    else
      image_tag 'no-image.png', class: "no-thumbnail thumbnail", size: '56x56'
    end
  end
  
  
  private
    def disable_showcase_option?
      puts "Spree::Product.showcased_items.map(&:id): #{Spree::Product.showcased_items.map(&:id)} / @product.id: #{@product.id}"
      return false if @product.new_record?
      showcased_ids = Spree::Product.showcased_items.map(&:id)
      return false if showcased_ids.size < 3 || showcased_ids.include?(@product.id)
      true
    end
    
    def page_decoy(direction)
      text = raw(send(:t, "views.pagination.#{direction}"))
      content_tag :span, text, class: 'pg-button page-step disabled'
    end
    
    def next_page_link(remote, url)
      link_to raw(t 'views.pagination.next'), url, rel: 'next', remote: remote, class: "pg-button page-step"
    end
    def prev_page_link(remote, url)
      link_to raw(t 'views.pagination.previous'), url, rel: 'prev', remote: remote, class: "pg-button page-step"
    end
  
end

app/views/spree/admin/products/_form.html.erb
<div data-hook="admin_product_form_fields">

  <div class="row">

    <div class="col-md-8" data-hook="admin_product_form_left">
      <div data-hook="admin_product_form_name">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', class: 'required')) %>
          <%= f.text_field :name, class: 'form-control title' %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_slug">
        <%= f.field_container :slug, class: ['form-group'] do %>
          <%= f.label :slug, raw(Spree.t(:slug) + content_tag(:span, ' *', class: "required")) %>
          <%= f.text_field :slug, class: 'form-control title' %>
          <%= f.error_message_on :slug %>
        <% end %>
      </div>
      
      <div data-hook="admin_product_form_retail_vendor_url">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :retail_vendor_url, Spree.t(:retail_vendor_url) %>
          <%= f.text_field :retail_vendor_url, class: 'form-control title' %>
          <%= f.error_message_on :retail_vendor_url %>
        <% end %>
      </div>
      
      <div data-hook="admin_product_form_description">
        <%= f.field_container :description, class: ['form-group'] do %>
          <%= f.label :description, Spree.t(:description) %>
          <%= f.text_area :description, { rows: "#{unless @product.has_variants? then '16' else '10' end}", class: 'form-control' } %>
          <%= f.error_message_on :description %>
        <% end %>
      </div>
      
      <div data-hook="admin_product_form_meta">
        <div data-hook="admin_product_form_meta_title">
          <%= f.field_container :meta_title, class: ['form-group'] do %>
            <%= f.label :meta_title, Spree.t(:meta_title) %>
            <%= f.text_field :meta_title, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_product_form_meta_keywords">
          <%= f.field_container :meta_keywords, class: ['form-group'] do %>
            <%= f.label :meta_keywords, Spree.t(:meta_keywords) %>
            <%= f.text_field :meta_keywords, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_product_form_meta_description">
          <%= f.field_container :meta_description, class: ['form-group'] do %>
            <%= f.label :meta_description, Spree.t(:meta_description) %>
            <%= f.text_field :meta_description, class: 'form-control' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-4" data-hook="admin_product_form_right">
      <div data-hook="admin_product_form_price">
        <%= f.field_container :price, class: ['form-group'] do %>
          <%= f.label :price, raw(Spree.t(:master_price) + content_tag(:span, ' *', class: "required")) %>
          <%= f.text_field :price, value: number_to_currency(@product.price, unit: ''), class: 'form-control', disabled: (cannot? :update, Spree::Price) %>
          <%= f.error_message_on :price %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_cost_price" class="alpha two columns">
        <%= f.field_container :cost_price, class: ['form-group'] do %>
          <%= f.label :cost_price, Spree.t(:cost_price) %>
          <%= f.text_field :cost_price, value: number_to_currency(@product.cost_price, unit: ''), class: 'form-control' %>
          <%= f.error_message_on :cost_price %>
        <% end %>
      </div>
      <div data-hook="admin_product_form_retail_vendor" class="two columns">
        <%= f.field_container :retail_vendor, class: ['form-group'] do %>
          <%= f.label :retail_vendor, Spree.t(:retail_vendor) %>
          <%= f.text_field :retail_vendor, class: 'form-control' %>
          <%= f.error_message_on :retail_vendor %>
        <% end %>
      </div>
      
      <% if @product.master_images.any? %>
        <div data-hook="admin_product_form_showcased">
          <%= f.field_container :showcased, class: ['form-group'] do %>
            <%= f.label :showcased, admin_showcased_products_label %>
            <%= f.error_message_on :showcased %>
            <%= showcased_check_box f %>
          <% end %>
        </div>
      <% end %>
      
      <div data-hook="admin_product_form_cost_currency" class="omega two columns">
        <%= f.field_container :cost_currency, class: ['form-group'] do %>
          <%= f.label :cost_currency, Spree.t(:cost_currency) %>
          <%= f.text_field :cost_currency, class: 'form-control' %>
          <%= f.error_message_on :cost_currency %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_available_on">
        <%= f.field_container :available_on, class: ['form-group'] do %>
          <%= f.label :available_on, Spree.t(:available_on) %>
          <%= f.error_message_on :available_on %>
          <%= f.text_field :available_on, value: datepicker_field_value(@product.available_on), class: 'datepicker form-control' %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_discontinue_on">
        <%= f.field_container :discontinue_on, class: ['form-group'] do %>
          <%= f.label :discontinue_on, Spree.t(:discontinue_on) %>
          <%= f.error_message_on :discontinue_on %>
          <%= f.text_field :discontinue_on, value: datepicker_field_value(@product.discontinue_on), class: 'datepicker form-control' %>
        <% end %>
      </div>

      <% if @product.has_variants? %>
        <div data-hook="admin_product_form_multiple_variants" class="well">
          <%= f.label :skus, Spree.t(:sku).pluralize %>
          <div class="info marginb">
            <%= Spree.t(:info_product_has_multiple_skus, count: @product.variants.size) %>
            <ul class="text_list">
              <% @product.variants.first(5).each do |variant| %>
                <li><%= variant.sku %></li>
              <% end %>
            </ul>
            <% if @product.variants.size > 5 %>
              <em>
                <%= Spree.t(:info_number_of_skus_not_shown, count: @product.variants.size - 5) %>
              </em>
            <% end %>
          </div>
          <div class="info-actions">
            <% if can?(:admin, Spree::Variant) %>
              <%= link_to_with_icon 'variants', Spree.t(:manage_variants), spree.admin_product_variants_url(@product), class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div data-hook="admin_product_form_sku">
          <%= f.field_container :sku, class: ['form-group'] do %>
            <%= f.label :sku, Spree.t(:sku) %>
            <%= f.text_field :sku, size: 16, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_product_form_promotionable">
          <%= f.field_container :promotionable, class: ['form-group'] do %>
              <%= f.label :promotionable, Spree.t(:promotionable) %>
              <%= f.error_message_on :promotionable %>
              <%= f.check_box :promotionable, class: 'form-control' %>
          <% end %>
        </div>

        <div id="shipping_specs" class="row">
          <div class="col-md-6">
            <div id="shipping_specs_weight_field" data-hook="admin_product_form_weight" class="form-group">
              <%= f.label :weight, Spree.t(:weight) %>
              <%= f.text_field :weight, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_height_field" data-hook="admin_product_form_height" class="form-group">
              <%= f.label :height, Spree.t(:height) %>
              <%= f.text_field :height, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_width_field" data-hook="admin_product_form_width" class="form-group">
              <%= f.label :width, Spree.t(:width) %>
              <%= f.text_field :width, size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-6">
            <div id="shipping_specs_depth_field" data-hook="admin_product_form_depth" class="form-group">
              <%= f.label :depth, Spree.t(:depth) %>
              <%= f.text_field :depth, size: 4, class: 'form-control' %>
            </div>
          </div>
        </div>
      <% end %>

      <div data-hook="admin_product_form_shipping_categories">
        <%= f.field_container :shipping_categories, class: ['form-group'] do %>
          <%= f.label :shipping_category_id, Spree.t(:shipping_categories) %>
          <%= f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', disabled: (cannot? :edit, Spree::ShippingCategory) }) %>
          <%= f.error_message_on :shipping_category %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_tax_category">
        <%= f.field_container :tax_category, class: ['form-group'] do %>
          <%= f.label :tax_category_id, Spree.t(:tax_category) %>
          <%= f.collection_select(:tax_category_id, @tax_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', disabled: (cannot? :edit, Spree::TaxCategory) }) %>
          <%= f.error_message_on :tax_category %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div data-hook="admin_product_form_taxons">
    <%= f.field_container :taxons, class: ['form-group'] do %>
      <%= f.label :taxon_ids, Spree.t(:taxons) %>

      <% if can? :modify, Spree::Classification %>
        <%= f.hidden_field :taxon_ids, value: @product.taxon_ids.join(',') %>
      <% elsif @product.taxons.any? %>
        <ul class="text_list">
          <% @product.taxons.each do |taxon| %>
            <li><%= taxon.name %></li>
          <% end %>
        </ul>
      <% else %>
        <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :taxons) %></div>
      <% end %>
    <% end %>
  </div>
  
  <div data-hook="admin_product_form_option_types">
    <%= f.field_container :option_types, class: ['form-group'] do %>
      <%= f.label :option_type_ids, Spree.t(:option_types) %>

      <% if can? :modify, Spree::OptionType %>
        <%= f.hidden_field :option_type_ids, value: @product.option_type_ids.join(',') %>
      <% elsif @product.option_types.any? %>
        <ul class="text_list">
          <% @product.option_types.each do |type| %>
            <li><%= type.presentation %> (<%= type.name %>)</li>
          <% end %>
        </ul>
      <% else %>
        <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :option_types) %></div>
      <% end %>
    <% end %>
  </div>
  
  
  
  
  <div data-hook="admin_product_form_additional_fields"></div>
  
</div>

app/views/spree/admin/products/data.html.erb
<% content_for :page_title do %>
  Data Import
<% end %>

<div class="row">
  <div id="content" class="col-sm-12" data-hook="">
    
    <div class="alert alert-info no-objects-found">
      <%= fa_icon("info-circle", text: 'Image import must be performed after successful import of product data') %>
    </div>
    
    <div class="row import-spreadsheet-row">
      <div id="bulk-import-skus-form" class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading"><h1 class="panel-title">Bulk Import SKUs</h1></div>
          <div class="panel-body">
            <%= form_for @spreadsheet, url: spree.admin_import_inventory_path(@spreadsheet), method: :post do |f| %>
              <fieldset data-hook="bulk-inventory-import">
                <div data-hook="bulk-inventory-import-form-fields" class="row">
                  <div class="col-md-6">
                    <div data-hook="file">
                      <%= f.label :data, Spree.t(:excel_file) %>
                      <%= f.file_field :data %>
                    </div>
                  </div>
                </div>
                <div class="form-actions" data-hook="buttons">
                  <%= button Spree.t(:import), 'download', 'submit', { class: 'btn-success' } %>
              
                  <span class="or"><%= Spree.t(:or) %></span>
                  <%= button_link_to Spree.t('actions.cancel'), spree.admin_products_url, icon: 'delete', id: 'cancel_link' %>
                </div>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
      
      <div id="generate-inventory-photos-form" class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h1 class="panel-title">Generate Inventory Photos</h1>
          </div>
          <div class="panel-body">
            <%= form_tag spree.admin_generate_variant_photos_path, html: { class: "navbar-form" } do |f| %>
              <fieldset data-hook="inventory-photo-generator">
                <div data-hook="inventory-photo-generator-form" class="row">
                  <div class="col-md-12">
                    <%= content_tag :span, "Source:", class: 'fyi' %>
                    <%= content_tag :span, "#{RAW_ASSET_DIRECTORY}#{BUCKET_PREFIX}", class: 'fyi-value' %>
                  </div>
                </div>
                <div class="form-actions" data-hook="buttons">
                  <%= button Spree.t(:process_images), 'picture', 'submit', { class: 'btn btn-success' } %>
                </div>
                <div class="mini-legend row">
                  <div class="col-md-12">
                    <%= content_tag :span, "Example file names: FT007C RED - 1.jpg or CH055D YEL-2.jpg", class: 'fyi-value' %>
                  </div>
                </div>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div id="bulk-import-legend" class="row">
      
    </div>
  </div>
</div>

app/views/spree/admin/products/index.html.erb
<!-- <span id="products-qs-info" class="label label-info">*Quick Search Now Uses SKU</span> -->
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Product) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_product), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_product' } %>
<% end if can?(:create, Spree::Product) %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">

    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = { f: f } %>
      <div data-hook="admin_products_index_search" class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, size: 15, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :variants_including_master_sku_cont, Spree.t(:sku) %>
            <%= f.text_field :variants_including_master_sku_cont, size: 15, class: "form-control js-quick-search-target" %>
          </div>
        </div>
        <div class="col-md-12">
          <div class="field checkbox">
            <label>
              <%= f.check_box :deleted_at_null, { checked: params[:q][:deleted_at_null] == '0'}, '0', '1' %>
              <%= Spree.t(:show_deleted) %>
            </label>
          </div>

          <div class="field checkbox">
            <label>
              <%= f.check_box :discontinue_on_null, { checked: params[:q][:discontinue_on_null] == '0' }, '0', '1' %>
              <%= Spree.t(:show_discontinued ) %>
            </label>
          </div>
        </div>
      </div>
      <div data-hook="admin_products_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>

  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @collection.any? %>
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:sku) %></th>
        <th><%= Spree.t(:status) %></th>

        <th colspan="2"><%= sort_link @search,:name, Spree.t(:name), { default_order: "desc" }, { title: 'admin_products_listing_name_title' } %></th>
        <th class="text-center">
          <%= sort_link @search, :master_default_price_amount, Spree.t(:master_price), {}, { title: 'admin_products_listing_price_title' } %>
        </th>
        <th data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="sku"><%= product.sku rescue '' %></td>
            <td class="status"><%= available_status(product) %> </td>
            <td class="image"><%= mini_image product %></td>
            <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="text-center"><%= product.display_price.to_html rescue '' %></td>
            <td class="actions actions-3 text-right" data-hook="admin_products_index_row_actions">
              <%= link_to_edit product, no_text: true, class: 'edit' if can?(:edit, product) && !product.deleted? %>
              <%= link_to_clone product, no_text: true, class: 'clone' if can?(:clone, product) %>
              <%= link_to_delete product, no_text: true if can?(:delete, product) && !product.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Product)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>